# Generated by Django 2.2 on 2020-10-19 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=15, verbose_name='Device Type')),
                ('location', models.CharField(max_length=5, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_type', models.CharField(choices=[('AG', 'Agent'), ('CU', 'Customer')], default='AG', max_length=5, verbose_name='User Type')),
                ('primary_phone', models.BigIntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('secondary_phone', models.BigIntegerField(blank=True, null=True, verbose_name='Secondary Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
