# Generated by Django 2.2.10 on 2020-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200618_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=200)),
                ('line_2', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('lga', models.CharField(max_length=40)),
            ],
        ),
    ]
