# Generated by Django 2.2 on 2020-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201020_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('AG', 'Agent'), ('CU', 'Customer')], default='CU', max_length=5, verbose_name='User Type'),
        ),
    ]
