# Generated by Django 2.2 on 2020-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201031_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_pin',
            field=models.IntegerField(default=0),
        ),
    ]
