# Generated by Django 2.2 on 2021-01-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201125_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo'),
        ),
    ]
